version: "3.8"
services:
  abogadosespecialistasenpensiones:
    image: "711324356654.dkr.ecr.us-east-1.amazonaws.com/hectorimages:latest"
    pull_policy: always
    restart: always
    networks:
      - caddy_network
    ports:
      - "3000:3000"
    
  caddy_reverse_proxy:
    image: caddy:latest
    restart: always
    networks:
      - caddy_network
    depends_on:
      - abogadosespecialistasenpensiones
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/ssl/certs/custom
      - ./private:/etc/ssl/private/custom
      - caddy_data:/data
      - caddy_config:/config
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dozzle:/data
    ports:
      - 8080:8080
    environment:
      DOZZLE_AUTH_PROVIDER: simple

networks:
  caddy_network:

volumes:
  caddy_data:
  caddy_config: